# Generated by Django 5.2.1 on 2025-05-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_collection_page_product_sociallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='social_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='SocialLink',
        ),
    ]
