# Generated by Django 5.2.1 on 2025-05-31 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_page_social_links_delete_sociallink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='social_links',
        ),
    ]
