# Generated by Django 5.2.1 on 2025-06-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currency',
            field=models.CharField(choices=[('LKR', 'LKR'), ('USD', 'USD')], default='LKR', max_length=3),
        ),
    ]
