from django.urls import path
from .views import (
    RegisterView, LogoutView, VerifyOTPView, CustomTokenObtainPairView,
    ResendOTPView, ForgotPasswordView, ResetPasswordView,
    PageDetailView, AddProductsView, AddProductsCSVView,
    ProfileDetailView, ProductListView, ProductDetailView,
    CollectionListView, CollectionDetailView, PublishPageView,
    PublicPagesListView, PublicPageDetailView, PublicProductsListView,
    PublicCollectionsListView, PublicProfileDetailView, CustomTokenRefreshView,
    UnpublishPageView, ClearCookiesView, storage_debug_view, ContactFormView,
)

urlpatterns = [
    path('user/register/', RegisterView.as_view(), name='register'),
    path('user/verify-otp/', VerifyOTPView.as_view(), name='verify_otp'),
    path('user/resend-otp/', ResendOTPView.as_view(), name='resend-otp'),
    path('login/', CustomTokenObtainPairView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('token/refresh/', CustomTokenRefreshView.as_view(), name='token_refresh'),
    path('forgot-password/', ForgotPasswordView.as_view(), name='forgot-password'),
    path('reset-password/', ResetPasswordView.as_view(), name='reset-password'),
    path('profile/', ProfileDetailView.as_view(), name='profile_detail'),
    path('page/', PageDetailView.as_view(), name='page_detail'),
    path('page/publish/', PublishPageView.as_view(), name='publish_page'),
    path('page/unpublish/', UnpublishPageView.as_view(), name='unpublish_page'),
    path('products/add/', AddProductsView.as_view(), name='add_products'),
    path('products/add-csv/', AddProductsCSVView.as_view(), name='add_products_csv'),
    path('products/', ProductListView.as_view(), name='product-list'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='product-detail'),
    path('collections/', CollectionListView.as_view(), name='collection-list'),
    path('collections/<int:pk>/', CollectionDetailView.as_view(), name='collection-detail'),
    path('pages/public/', PublicPagesListView.as_view(), name='public_pages_list'),
    path('page/public/<int:id>/', PublicPageDetailView.as_view(), name='public_page_detail'),
    path('products/public/<int:page_id>/', PublicProductsListView.as_view(), name='public_products_list'),
    path('collections/public/<int:page_id>/', PublicCollectionsListView.as_view(), name='public_collections_list'),
    path('profile/public/<int:page_id>/', PublicProfileDetailView.as_view(), name='public_profile_detail'),
    path('clear-cookies/', ClearCookiesView.as_view(), name='clear_cookies'),
    path('storage-debug/', storage_debug_view),
    path('contact/', ContactFormView.as_view(), name='contact_form'),
]