import React from "react";
import Navbar from "../components/NavBar";
import "../styles/PrivacyPolicy.css";
import { FaShieldAlt, FaEye, FaCookie, FaChartBar, FaGavel, FaEnvelope, FaUserLock } from 'react-icons/fa';
import { FaInstagram, FaGithub } from 'react-icons/fa';
import { FaXTwitter } from 'react-icons/fa6';

const navLinks = [
  { href: "/landingpage", label: "Home" },
  { href: "/about", label: "About Us" },
  { href: "/contact", label: "Contact Us" },
];

const PrivacyPolicy = () => (
  <div className="privacy-gradient-bg">
    <Navbar links={navLinks} />
    <div className="privacy-container">
      <h1 className="privacy-title"><FaShieldAlt className="privacy-title-icon" /> Privacy Policy</h1>
      <p className="privacy-updated">Last updated: June 7, 2025</p>
      <div className="privacy-card glass-card">
        <h2><FaEye className="privacy-section-icon" /> Information Collection</h2>
        <p>We collect information you provide directly (such as name, email, preferences, and content you create) and data generated by your use of our platform (such as decision counters, preferences, and analytics). We do not sell your personal information.</p>
      </div>
      <div className="privacy-card glass-card">
        <h2><FaCookie className="privacy-section-icon" /> Cookies</h2>
        <p>We use cookies and similar technologies to enhance your experience, remember your preferences, and keep you logged in. Essential cookies are required for site functionality. You may disable cookies in your browser, but some features may not work as intended.</p>
      </div>
      <div className="privacy-card glass-card">
        <h2><FaChartBar className="privacy-section-icon" /> Third-party Ads & Analytics</h2>
        <p>We may display third-party advertisements (such as Google AdSense). These partners may use cookies or similar technologies to personalize ads. We use analytics tools to understand how our platform is used and to improve your experience. These tools may collect anonymized usage data. No personally identifiable information is shared with analytics providers.</p>
      </div>
      <div className="privacy-card glass-card">
        <h2><FaChartBar className="privacy-section-icon" /> Data Usage for Decision Counters & Preferences</h2>
        <p>We use your data to provide personalized features, such as decision counters and saving your preferences. This data is never sold or used for profiling beyond the scope of our platform.</p>
      </div>
      <div className="privacy-card glass-card">
        <h2><FaUserLock className="privacy-section-icon" /> Your Rights (GDPR)</h2>
        <p>If you are located in the EU, you have the right to access, correct, or delete your personal data, and to object to or restrict certain processing. To exercise your rights, please contact us using the information below.</p>
      </div>
      <div className="privacy-card glass-card">
        <h2><FaEnvelope className="privacy-section-icon" /> Contact Information</h2>
        <p>If you have any questions or requests regarding your privacy, please email us at <a href="mailto:support@creatimate.com">support@creatimate.com</a> or use our <a href="/contact">contact form</a>.</p>
      </div>
      <div className="privacy-card glass-card privacy-legal">
        <p>This policy may be updated from time to time. We encourage you to review it regularly. Continued use of our platform constitutes acceptance of this policy.</p>
      </div>
    </div>
    <footer className="footer-section">
      <div className="footer-container">
        <div className="footer-column">
          <h4>Quick Links</h4>
          <ul>
            <li><a href="/about">About</a></li>
            <li><a href="/privacy-policy">Privacy Policy</a></li>
            <li><a href="/terms-of-service">Terms of Service</a></li>
            <li><a href="/contact">Contact Us</a></li>
          </ul>
        </div>
        <div className="footer-column">
          <h4>Follow Us</h4>
          <div className="footer-social-links">
            <a href="https://instagram.com/justy__11" target="_blank" rel="noopener noreferrer" aria-label="Instagram">
              <FaInstagram size={24} color="#E1306C" />
            </a>
            <a href="https://github.com/Justy-11" target="_blank" rel="noopener noreferrer" aria-label="GitHub">
              <FaGithub size={24} color="#fff" />
            </a>
            <a href="https://x.com/justy0011" target="_blank" rel="noopener noreferrer" aria-label="X">
              <FaXTwitter size={24} color="#1da1f2" />
            </a>
          </div>
        </div>
        <div className="footer-column">
          <h4>About This Site</h4>
          <p>Made with <span className="privacy-heart">♥</span> to empower creators and small businesses everywhere.</p>
          <p className="privacy-footer-copy">© 2025 CreatiMate. All rights reserved.</p>
        </div>
      </div>
    </footer>
  </div>
);

export default PrivacyPolicy;
